### ISSUE TITLE
Anonymous users cannot initiate multipart uploads.  Please authenticate.

### ISSUE THREAD

**Issue by ftago** [rdblue/s3committer#7]
Channel is closed. Failed to relay message
17/07/20 02:34:53 WARN TaskSetManager: Lost task 22.2 in stage 0.0 (TID 87, ip-172-31-22-106.us-west-2.compute.internal, executor 6): com.azonS3Exception: Anonymous users cannot initiate multipart uploads.  Please authenticate. (Service: Amazon S3; Status Code: 403; Error Code:E1A0113F5ED10), S3 Extended Request ID: 7dGGvSrKI4bN9gIVjJYsPlmgF2Am5hP70eUGzJn1ihLPUBumgjPyRry1AK6f2tHg9LN+RT76ZYI=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:2708)
        at com.netflix.bdp.s3.S3Util.multipartUpload(S3Util.java:73)
        at com.netflix.bdp.s3.S3MultipartOutputCommitter$8.run(S3MultipartOutputCommitter.java:438)
        at com.netflix.bdp.s3.S3MultipartOutputCommitter$8.run(S3MultipartOutputCommitter.java:426)
        at com.netflix.bdp.s3.Tasks$Builder.runSingleThreaded(Tasks.java:107)
        at com.netflix.bdp.s3.Tasks$Builder.run(Tasks.java:93)

**Comment by ftago** [comment]
can anyone tell me why I am facing this issue ?

**Comment by palakpsheth** [comment]
@ftago Did you ever find a solution? I am hitting the same issue...thanks!

**Comment by ftago** [comment]
Hi Palakpsheth  
sorry for the late reply.
I used the hadoofp configuration credentials as a workaround for the moment

**Comment by rdblue** [comment]
This is an authentication error, not related to the committers.

**Comment by zentraedi** [comment]
Hi everyone,

I know this issue was closed long ago, but I'm getting this error too. I've tried setting the credentials in Hadoop config as well to no avail.

When I test the multipart upload through S3 CLI I can do it with no problems. Likewise, when I use Spark's default comitter I can upload with no issues to S3.

How did you guys solved it?

Thanks,

**Comment by softarts** [comment]
I got this issue too. although I set the bucket policy as 'public'

**Comment by ManuelMourato25** [comment]
@zentraedi , @softarts  were you able to solve this issue?
I also can upload to S3 with the default commiter with no issue.
But with this one I get a similiar error:
```
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: E642B9D74F1D037D; S3 Extended Request ID: 4qYOoaaZ8zrtXPrKqbf1AIiA6knW2vXMfje+ivxABbP6rK20XfJ7Kz5lNYbk7tZrtC6po0gAkfM=), S3 Extended Request ID: 4qYOoaaZ8zrtXPrKqbf1AIiA6knW2vXMfje+ivxABbP6rK20XfJ7Kz5lNYbk7tZrtC6po0gAkf
```
